export default [
  {
    image: "./assets/html.png",
    description: "Web Development Languages",
    title: "HTML",
    author: "Sarah Smith",
    rating: 80,
  },
  {
    image: "./assets/javascript.jpg",
    description: "Web Development Languages",
    title: "Angular",
    author: "David Lee",
    rating: 70,
  },
  {
    image: "./assets/jquery.png",
    description: "Frontend Frameworks and Libraries",
    title: "jQuery",
    author: "John Johnson",
    rating: 80,
  },
  {
    image: "./assets/angular.png",
    description: "Web Development Languages",
    title: "JavaScript",
    author: "Emily Chen",
    rating: 80,
  },
  {
    image: "./assets/react.webp",
    description: "Frontend Frameworks and Libraries",
    title: "React",
    author: "Daniel Brown",
    rating: 80,
  },
  {
    image: "./assets/vuejs.jpeg",
    description: "Frontend Frameworks and Libraries",
    title: "Vue.js",
    author: "Ava Jones",
    rating: 75,
  },
  {
    image: "./assets/nodejs.webp",
    description: "Backend Frameworks and Libraries",
    title: "Node.js",
    author: "Micheal Kim",
    rating: 80,
  },
  {
    image: "./assets/expressjs.webp",
    description: "Backend Frameworks and Libraries",
    title: "Express.js",
    author: "Sophia Rodriguez",
    rating: 80,
  },
  {
    image: "./assets/ruby.jpeg",
    description: "Backend Frameworks and Libraries",
    title: "Ruby and Rails",
    author: "William Lee",
    rating: 60,
  },
  {
    image: "./assets/accessibility.png",
    description: "Frontend Frameworks and Libraries",
    title: "Accessability",
    author: "John Doe",
    rating: 95,
  },
  {
    image: "./assets/ajax.gif",
    description: "Frontend Frameworks and Libraries",
    title: "Ajax",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/ci-cd.jpeg",
    description: "Backend Frameworks and Libraries",
    title: "CI/CD",
    author: "John Doe",
    rating: 90,
  },
  {
    image: "./assets/cloud.jpeg",
    description: "Backend Frameworks and Libraries",
    title: "Cloud",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/cms.png",
    description: "Backend Frameworks and Libraries",
    title: "CMS",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/design-systems.jpeg",
    description: "Backend Frameworks and Libraries",
    title: "Design Systems",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/devops.png",
    description: "Backend Frameworks and Libraries",
    title: "Devops",
    author: "John Doe",
    rating: 55,
  },
  {
    image: "./assets/django.jpeg",
    description: "Backend Frameworks and Libraries",
    title: "Django",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/docker.png",
    description: "Backend Frameworks and Libraries",
    title: "Devops",
    author: "John Doe",
    rating: 50,
  },
  {
    image: "./assets/flask.webp",
    description: "Backend Frameworks and Libraries",
    title: "Flask",
    author: "John Doe",
    rating: 80,
  },
  {
    image: "./assets/graphql.png",
    description: "Backend Frameworks and Libraries",
    title: "GraphQL",
    author: "John Doe",
    rating: 50,
  },
  {
    image: "./assets/json.png",
    description: "Backend Frameworks and Libraries",
    title: "JSON",
    author: "John Doe",
    rating: 70,
  },
];